mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("todoist.urls")),
    path('admin/', admin.site.urls),
]

mysite/todoist/urls.py
from django.urls import path

from . import views

app_name = "todoist"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:bloco_id>/delete/", views.delete, name="delete"),
    path("<int:bloco_id>/update/", views.update, name="update"),
    path("create", views.create, name="create"),
    path("login", views.login, name="login"),
    path("create-account", views.create_account, name="create-account"),
    path("logout", views.encerrar_sessao, name="encerrar_sessao")
]

mysite/todoist/models.py
import datetime
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


class Bloco(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        null=True
    )
    bloco_titulo = models.CharField(max_length=200)
    bloco_texto = models.CharField(max_length=500)
    data_pub = models.DateTimeField("data de criação")

    def __str__(self):
        return self.bloco_titulo

    def criado_recentemente(self):
        return self.data_pub >= timezone.now() - datetime.timedelta(days=1)

mysite/todoist/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Bloco
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout
from django.db.models import Q


def create_account(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts/login/")

    context = {'form': form}

    return render(request, 'todoist/create-account.html', context)


def index(request):
    # pega todos os blocos
    bloco_list = __retorna_blocos(request)
    # carrega o template index
    template = loader.get_template("todoist/index.html")
    # adiciona a lista dos blocos em uma lista de contexto
    context = {
        "bloco_list": bloco_list,
    }
    # retorna a resposta HTTP renderizando o template com a lista de blocos
    return HttpResponse(template.render(context, request))


def create(request):
    titulo = request.POST.get("titulo", "")
    texto = request.POST.get("texto", "")
    data = request.POST.get("data", "")
    bloco = Bloco(bloco_titulo=titulo, bloco_texto=texto, data_pub=data)
    if request.user.is_authenticated:
        bloco.user = request.user
    bloco.save()
    return HttpResponseRedirect(reverse("todoist:index"))


def update(request, bloco_id):
    bloco = get_object_or_404(Bloco, pk=bloco_id)
    bloco.bloco_titulo = request.POST.get("titulo", "")
    bloco.bloco_texto = request.POST.get("texto", "")
    bloco.data_pub = request.POST.get("data", "")
    bloco.save()
    return HttpResponseRedirect(reverse("todoist:index"))


def delete(request, bloco_id):
    bloco = get_object_or_404(Bloco, pk=bloco_id)
    if len(__retorna_blocos(request)) > 1:
        bloco.delete()
    return HttpResponseRedirect(reverse("todoist:index"))


def login(request):
    return render(request, "todoist/login.html")


def encerrar_sessao(request):
    logout(request)
    return HttpResponseRedirect(reverse("todoist:index"))


# def create_account(request):
#    return render(request, "todoist/create-account.html")


def __retorna_blocos(request):
    if request.user.is_authenticated:
        result = Bloco.objects.filter(Q(user=request.user) | Q(user__isnull=True))
    else:
        result = Bloco.objects.filter(user__isnull=True)
    return result

mysite/todoist/templates/todoist/create-account.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Account</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #3D2350;
            margin: 0;
            padding: 0;
        }

        .container {
            margin: 100px auto;
            width: 300px;
            background-color: #271633;
            border: 2px solid black;
            border-radius: 10px;
            padding: 20px;
            text-align: center;
        }

        h1 {
            color: white;
            font-size: 1.5rem;
            margin-top: 0;
        }

        input[type="text"],
        input[type="email"],
        input[type="password"] {
            width: calc(100% - 40px);
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        button {
            width: calc(100% - 40px);
            padding: 10px;
            margin: 10px 0;
            background-color: #007bff;
            border: none;
            border-radius: 5px;
            color: white;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        .container p {
            color: white;
            font-size: 14px;
            margin-top: 10px;
        }

        .container p a {
            color: #007bff;
            text-decoration: none;
        }

        .container p a:hover {
            text-decoration: underline;
        }

        ul{
            list-style-type: circle;
        }

        #id_username_helptext{
            color: rgb(153, 153, 153);
        }

        li{
            font-size: 0.8rem;
            font-style: italic;
            padding-bottom: 10px;
            color: rgb(153, 153, 153);
            text-decoration: underline;
        }

        .errorlist li{
            color: red;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Create Account</h1>
        <form class="register-form" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Create Account</button>
        </form>
        <p>Already have account? <a rel="prev" href="accounts/login/">Sign in</a>.</p>
    </div>
</body>
</html>

mysite/todoist/templates/todoist/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static  'todoist/css/style.css' %}">
    <link rel="stylesheet" href="{% static  'todoist/css/reset.css' %}">
    <link rel="shortcut icon" href="{% static  'todoist/img/favicon.ico' %}" type="image/x-icon">
    <title>Bloco de Notas</title>
</head>
<body>
    <header>
        <nav>
            <ul class="header-ul">
                <li>
                    <div class="user" id="userMenu">
                        <img id="userPhoto" src="{% static  'todoist/img/user.png' %}" alt="">
                        <ul class="menu">
                            <li><a href="#" id="changeImage">Mudar Imagem</a></li>
                            <li><a href="#">Sair da Conta</a></li>
                        </ul>
                    </div>
                    <input type="file" id="fileInput" style="display: none;">
                </li>
                <li class="logo">
                    <a href="#"><img class="logo-img" src="{% static  'todoist/img/icon.png' %}" alt=""></a>
                </li>
                {% if not request.user.is_authenticated %}
                <li class="Login">
                    <button id="loginButton"><a rel="next" href="accounts/login/">Login</a></button>
                </li>
                {% else %}
                <li class="Login">
                    <button id="logoutButton"><a href="{% url 'todoist:encerrar_sessao' %}">Logout</a></button>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <nav>
            <a class="add-button" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" type id="button" class="bi bi-plus-square" viewBox="0 0 16 16">
                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                </svg>
            </a>
        </nav>
        <div class="main-container">
            <img class="flag-img" src="{% static  'todoist/img/Flag.png' %}" alt="">
            <ul class="block-ul">
                {% if bloco_list %}
                    {% for bloco in bloco_list %}
                        <form class="formulario" action="{% url 'todoist:update' bloco.id %}" method="post">
                            {% csrf_token %}
                            <li class="block-list">
                                <div class="block">
                                    <div class="block-header">
                                        <div class="input-wrapper">
                                            <input class="title-input"  name="titulo" placeholder="Title" maxlength="10" type="text" value="{{ bloco.bloco_titulo}}">
                                        </div>
                                        <div class="icon-wrapper">
                                            <a href="{% url 'todoist:delete' bloco.id %}" id="exclude-form"><i class="fa-solid fa-circle-xmark"></i></a>
                                        </div>
                                    </div>
                                    <div class="input-container"><textarea name="texto" rows="24" cols="39">{{ bloco.bloco_texto}}</textarea></div>
                                    <input type="hidden" value="{{bloco.id}}" name="id">
                                    <div class="submit-button">
                                        <input class="submit-input" type="submit" value="Save">
                                        <div class="date-wrapper">
                                            <input class="datetime-local" name="data" placeholder="Date" maxlength="10" type="datetime-local" value="{{ bloco.data_pub|date:'Y-m-d' }}T{{bloco.data_pub|time:'H:i'}}">
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </form>
                    {% endfor %}
                {% endif%}
            </ul>
        </div>
    </main>
    <footer>
        <div class="container">
            <div class="footer-content footer-content-j">
                <h2>João Vitor Oliveira</h2>
                <p>Desenvolvedor Web FrontEnd</p>
                <p>Email: joao.vit.maiaoliv@gmail.com</p>
                <p>Telefone: +55 11-963415901</p>
                <p>Github: <a target="_blank" href="https://github.com/JoaoVitMaia">JoaoVitMaia</a></p><br>
            </div>
            <div class="footer-content footer-content-l">
                <h2>Leonardo Yuri</h2>
                <p>Desenvolvedor Web BackEnd</p>
                <p>Email: leonardo.yuri.ms@gmail.com</p>
                <p>Telefone: +55 11-963415901</p>
                <p>Github: <a target="_blank" href="https://github.com/LeoYuriM">LeoYuriM</a></p>
            </div>
        </div>
    </footer>
    <script src="{% static  'todoist/js/script.js' %}"></script>
    <script src="https://kit.fontawesome.com/d8f0912581.js" crossorigin="anonymous"></script>
</body>
</html>

mysite/todoist/templates/todoist/login.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static  'todoist/css/reset.css' %}">
    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #3D2350;
            margin: 0;
            padding: 0;
        }

        .container {
            margin: 100px auto;
            width: 300px;
            background-color: #271633;
            border: 2px solid black;
            border-radius: 10px;
            padding: 20px;
            text-align: center;
        }

        h1 {
            color: white;
            font-size: 1.5rem;
            margin-top: 0;
        }

        input[type="text"],
        input[type="password"] {
            width: calc(100% - 40px);
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        button {
            width: calc(100% - 40px);
            padding: 10px;
            margin: 10px 0;
            background-color: #007bff;
            border: none;
            border-radius: 5px;
            color: white;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        .container p {
            color: white;
            font-size: 14px;
            margin-top: 10px;
        }

        .container p a {
            color: #007bff;
            text-decoration: none;
        }

        .container p a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Login</h1>
        <form class="login-form">
            <input type="text" placeholder="Usuário" required>
            <input type="password" placeholder="Senha" required>
            <button type="submit">Entrar</button>
        </form>
        <p>Não tem uma conta? <a href="{% url 'todoist:create-account' %}">Crie uma aqui</a>.</p>

    </div>
</body>
</html>